components:
    schemas:
        TestrayRunComparison:
            properties:
                results:
                    items:
                        type: object
                    type: array
                testrayCasePriorities:
                    type: string
                testrayTeamId:
                    format: int64
                    type: integer
            type: object
info:
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Testray REST"
    version: v1.0
openapi: 3.0.1
paths:
    "/testray-run-comparisons/{testrayRunId1}/{testrayRunId2}":
        get:
            operationId: getTestrayRunComparison
            parameters:
                - in: path
                  name: testrayRunId1
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: path
                  name: testrayRunId2
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: testrayCasePriorities
                  schema:
                      type: string
                - in: query
                  name: testrayTeamId
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/TestrayRunComparison"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/TestrayRunComparison"
            tags: ["TestrayRunComparison"]